/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.dur.opa.view;

import pl.dur.opa.controllers.ClientController;

/**
 *
 * @author Dur
 */
public class LoggingPage extends javax.swing.JFrame
{
	private ClientController controller;
	/**
	 * Creates new form LoggingPage
	 */
	public LoggingPage(ClientController controller )
	{
		this.controller = controller;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginTF = new javax.swing.JTextField();
        ServerAddressTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        serverAddresL = new javax.swing.JLabel();
        loginL = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        tekstL = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginTF.setText("ddr");

        ServerAddressTF.setText("localhost");

        passwordTF.setText("ddr");

        serverAddresL.setText("Server Address");

        loginL.setText("Login");

        passwordL.setText("Password");

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoginAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tekstL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginTF)
                                    .addComponent(ServerAddressTF)
                                    .addComponent(passwordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serverAddresL)
                                    .addComponent(passwordL)
                                    .addComponent(loginL)))
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServerAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverAddresL))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginL))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordL))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tekstL, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void onLoginAction( java.awt.event.ActionEvent evt )//GEN-FIRST:event_onLoginAction
	{//GEN-HEADEREND:event_onLoginAction
		char[] pass = passwordTF.getPassword();
		String password = String.valueOf( pass );
		if( ServerAddressTF.getText().length() == 0 || loginTF.getText().length() == 0 || password.
				length() == 0 )
		{
			tekstL.setText( "You must specify all informations to connect to server " );
		}
		else
		{
			tekstL.setText( "" );
			if( controller.connectToServer( loginTF.getText(), password, ServerAddressTF.getText()) == true )
			{
				this.setVisible( false );
			}
			else
			{
				tekstL.setText( "Could not connect to server" );
			}
		}
	}//GEN-LAST:event_onLoginAction
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ServerAddressTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginL;
    private javax.swing.JTextField loginTF;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel serverAddresL;
    private javax.swing.JLabel tekstL;
    // End of variables declaration//GEN-END:variables
}
